name: Build my application

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Print Current Directory"
        run: pwd
      - uses: actions/checkout@v2
        
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build
        
        
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      
      - name : Check dotnet 
        run: dotnet --version
        
      - name : Check node
        run: node --version
        

