name: Build my application

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Print Current Directory"
        run: pwd
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test